modLoader = "kotlinforforge"
loaderVersion = "[5.8.0,)"
license = "GPL-3.0"

[[mixins]]
config = "mixins.sbwnpc.json"

[[mods]]
modId = "sbwnpc"
version = "0.3.1-dev"
displayName = "[SBW] NPC Squads"
authors = "fr3ddy"
description = "NPC squads addon for SuperbWarfare"

[[dependencies.sbwnpc]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.203,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sbwnpc]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sbwnpc]]
modId = "superbwarfare"
type = "required"
versionRange = "[0.8.9.1,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.sbwnpc]]
modId = "smartbrainlib"
type = "required"
versionRange = "[1.16.11,)"
ordering = "AFTER"
side = "BOTH"
